trigger:
  tags:
    include:
    - '*'
  branches:
    exclude:
    - master

jobs:
  - job: Deploy to Nuget
    condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
    pool:
      vmImage: 'macOS-latest'
    timeoutInMinutes: 5
    steps:
      - script: |
        dotnet tool restore
        dotnet cake --configuration release --version 1.1
        dotnet cake --target Nuget --version 1.1
      displayName: 'Deploy'
