trigger:
  tags:
    include:
    - '*'
  branches:
    exclude:
    - master

jobs:
  - job: 'Deploy'
    condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
    pool:
      vmImage: 'macOS-latest'
    timeoutInMinutes: 5
    variables:
    - name : tagName
      value: $[ replace(variables['Build.SourceBranch'], 'refs/tags/', '') ] 
    steps:
      - script: |
          dotnet tool restore
          dotnet cake --configuration release --release-version $(tagName)
          dotnet cake --target Nuget --release-version $(tagName)
        displayName: 'Deploy'
